// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QCSingleTrack.Infrastructure.Data;

#nullable disable

namespace QCSingleTrack.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TrailStatusDbContext))]
    [Migration("20251124185503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QCSingleTrack.Domain.CurrentStatus", b =>
                {
                    b.Property<int>("TrailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastScrapedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TrailId");

                    b.ToTable("CurrentStatus", (string)null);
                });

            modelBuilder.Entity("QCSingleTrack.Domain.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrailId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("TrailName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TrailId");

                    b.ToTable("Trails", (string)null);
                });

            modelBuilder.Entity("QCSingleTrack.Domain.CurrentStatus", b =>
                {
                    b.HasOne("QCSingleTrack.Domain.Trail", "Trail")
                        .WithOne("CurrentTrailStatus")
                        .HasForeignKey("QCSingleTrack.Domain.CurrentStatus", "TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("QCSingleTrack.Domain.Trail", b =>
                {
                    b.Navigation("CurrentTrailStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
